/** Sidebar navigation structure */
export const NAV_SECTIONS = [
  {
    label: 'Overview',
    items: [
      { id: 'overview', label: 'Overview dashboard' },
    ],
  },
  {
    label: 'AI companies',
    sectorId: 'companies',
    items: [
      { id: 'demand-openai',     label: 'OpenAI / ChatGPT'   },
      { id: 'demand-anthropic',  label: 'Anthropic / Claude' },
      { id: 'demand-google',     label: 'Google / Gemini'    },
      { id: 'demand-zhipu',      label: 'Zhipu AI / GLM'     },
      { id: 'demand-minimax',    label: 'MiniMax'            },
    ],
  },
  {
    label: 'Market signals',
    items: [
      { id: 'market-signals', label: 'Market signals' },
    ],
  },
  {
    label: 'Supply chain',
    sectorId: 'supply',
    mode: 'supply',
    items: [
      { id: 'ai-supply-optics',    label: 'Optics supply chain'    },
      { id: 'ai-supply-fiber',     label: 'Fiber supply chain'     },
      { id: 'ai-supply-ccl',       label: 'CCL supply chain'       },
      { id: 'ai-supply-pcb',       label: 'PCB supply chain'       },
      { id: 'ai-supply-abf',       label: 'ABF supply chain'       },
      { id: 'ai-supply-mlcc',      label: 'MLCC supply chain'      },
      { id: 'ai-supply-cooling',   label: 'Cooling supply chain'   },
      { id: 'ai-supply-power',     label: 'Power supply chain'     },
      { id: 'ai-supply-equipment', label: 'Equipment supply chain' },
      { id: 'ai-supply-memory',    label: 'Memory supply chain'    },
      { id: 'ai-supply-foundry',   label: 'Foundry supply chain'   },
      { id: 'ai-supply-trainium',  label: 'Trainium supply chain'  },
      { id: 'ai-supply-cpu',       label: 'CPU supply chain'       },
      { id: 'ai-supply-odm',       label: 'ODM supply chain'       },
    ],
  },
  {
    label: 'AI supply chain',
    sectorId: 'aisupplychain',
    mode: 'aisupplychain',
    items: [
      { id: 'dc-capacity',     label: 'Overview'                },
      { id: 'dc-co-aws',       label: 'Amazon AWS'              },
      { id: 'dc-co-google',    label: 'Google'                  },
      { id: 'dc-co-microsoft', label: 'Microsoft'               },
      { id: 'dc-co-oracle',    label: 'Oracle'                  },
      { id: 'dc-co-openai',    label: 'OpenAI'                  },
      { id: 'dc-co-nebius',    label: 'Nebius'                  },
      { id: 'dc-co-meta',      label: 'Meta'                    },
    ],
  },
  {
    label: 'Markets',
    mode: 'tool',
    items: [
      { id: 'sentiment', label: 'Sentiment & options' },
      { id: 'options',   label: 'Options flow' },
    ],
  },
  {
    label: 'Market Performance',
    sectorId: 'market-performance',
    mode: 'us-performance',
    items: [
      { id: 'us-performance',       label: 'US' },
      { id: 'hk-china-performance', label: 'HK/China' },
    ],
  },
  {
    label: 'Leverage',
    sectorId: 'leverage',
    mode: 'leverage',
    items: [
      { id: 'leverage-korea',    label: 'Korea'  },
      { id: 'leverage-taiwan',   label: 'Taiwan' },
      { id: 'taiwan-individual', label: 'Taiwan individual' },
      { id: 'leverage-china',    label: 'A shares' },
      { id: 'leverage-japan',    label: 'Japan' },
      { id: 'leverage-us',       label: 'US' },
    ],
  },
  {
    label: 'Liquidity',
    sectorId: 'liquidity',
    mode: 'liquidity',
    items: [
      { id: 'liquidity-china-flow', label: 'China' },
    ],
  },
  {
    label: 'Transcripts',
    mode: 'tool',
    items: [
      { id: 'transcripts', label: 'Earnings transcript agent' },
    ],
  },
  {
    label: 'Sources',
    mode: 'tool',
    items: [
      { id: 'sources', label: 'Data validity' },
    ],
  },
  {
    label: 'Pricing',
    sectorId: 'pricing',
    mode: 'pricing',
    items: [
      { id: 'pricing-memory', label: 'Memory'    },
      { id: 'pricing-gpu',    label: 'GPU'       },
      { id: 'pricing-aws',    label: 'AWS Chips' },
      { id: 'pricing-cpu',    label: 'CPU'       },
      { id: 'pricing-tpu',    label: 'TPU'       },
    ],
  },
];

/** Page title shown in the top bar, keyed by view id. */
export const VIEW_META = {
  overview:           { title: 'OVERVIEW DASHBOARD' },
  // Company demand pages
  'demand-openai':    { title: 'OPENAI / CHATGPT' },
  'demand-anthropic': { title: 'ANTHROPIC / CLAUDE' },
  'demand-google':    { title: 'GOOGLE / GEMINI' },
  'demand-zhipu':     { title: 'ZHIPU AI / GLM' },
  'demand-minimax':   { title: 'MINIMAX' },
  'market-signals':        { title: 'MARKET SIGNALS' },
  'demand-general':        { title: 'INFRASTRUCTURE & OSS SIGNALS' },
  'openrouter-rankings':   { title: 'OPENROUTER MODEL RANKINGS' },
  // Source-specific signal pages — reachable via direct navigation or Ask tab
  pypi:              { title: 'PYPI / NPM' },
  github:            { title: 'GITHUB DEPENDENTS' },
  web:               { title: 'WEB TRAFFIC & STICKINESS' },
  hf:                { title: 'HUGGINGFACE DOWNLOADS' },
  pricing:           { title: 'PRICING — GPU & MEMORY SPOT' },
  'pricing-memory':  { title: 'PRICING — MEMORY SPOT' },
  'pricing-gpu':     { title: 'PRICING — GPU SPOT' },
  'pricing-aws':     { title: 'PRICING — AWS AI-CHIP SPOT' },
  'pricing-cpu':     { title: 'PRICING — CPU SPOT' },
  'pricing-tpu':     { title: 'PRICING — TPU PREEMPTIBLE' },
  datacenter:        { title: 'US DATACENTER BUILD' },
  electricity:       { title: 'AI ELECTRICITY DEMAND' },
  chinese:           { title: 'CHINESE LLM USAGE' },
  'ai-supply-optics':    { title: 'AI SUPPLY — OPTICS' },
  'ai-supply-fiber':     { title: 'AI SUPPLY — FIBER' },
  'ai-supply-ccl':       { title: 'AI SUPPLY — CCL' },
  'ai-supply-pcb':       { title: 'AI SUPPLY — PCB' },
  'ai-supply-abf':       { title: 'AI SUPPLY — ABF' },
  'ai-supply-mlcc':      { title: 'AI SUPPLY — MLCC' },
  'ai-supply-cooling':   { title: 'AI SUPPLY — COOLING' },
  'ai-supply-power':     { title: 'AI SUPPLY — POWER' },
  'ai-supply-equipment': { title: 'AI SUPPLY — EQUIPMENT' },
  'ai-supply-memory':    { title: 'AI SUPPLY — MEMORY' },
  'ai-supply-foundry':   { title: 'AI SUPPLY — FOUNDRY' },
  'ai-supply-trainium':  { title: 'AI SUPPLY — TRAINIUM' },
  'ai-supply-cpu':       { title: 'AI SUPPLY — CPU' },
  'ai-supply-odm':       { title: 'AI SUPPLY — ODM' },
  'dc-capacity':      { title: 'AI SUPPLY CHAIN — OVERVIEW' },
  'dc-timelines':     { title: 'AI SUPPLY CHAIN — COMPANY BUILDOUT TIMELINES' },
  'dc-co-aws':        { title: 'AI SUPPLY CHAIN — AMAZON AWS' },
  'dc-co-google':     { title: 'AI SUPPLY CHAIN — GOOGLE' },
  'dc-co-microsoft':  { title: 'AI SUPPLY CHAIN — MICROSOFT' },
  'dc-co-oracle':     { title: 'AI SUPPLY CHAIN — ORACLE' },
  'dc-co-openai':     { title: 'AI SUPPLY CHAIN — OPENAI' },
  'dc-co-nebius':     { title: 'AI SUPPLY CHAIN — NEBIUS' },
  'dc-co-meta':       { title: 'AI SUPPLY CHAIN — META' },
  'github-commits':   { title: 'GITHUB COMMIT VELOCITY' },
  docker:             { title: 'DOCKER HUB DEPLOYS' },
  community:          { title: 'HN PULSE' },
  options:            { title: 'OPTIONS FLOW' },
  alerts:             { title: 'DAILY OPTIONS REPORT' },
  sentiment:          { title: 'MARKETS — SENTIMENT & OPTIONS' },
  'us-performance':   { title: 'MARKET PERFORMANCE — US' },
  'hk-china-performance': { title: 'MARKET PERFORMANCE — HK/CHINA' },
  'leverage-korea':   { title: 'LEVERAGE — KOREAN RETAIL FIREPOWER' },
  'leverage-taiwan':  { title: 'LEVERAGE — TAIWAN RETAIL FIREPOWER' },
  'taiwan-individual': { title: 'TAIWAN — INDIVIDUAL STOCK MARGIN' },
  'leverage-china':   { title: 'LEVERAGE — CHINA A-SHARES' },
  'leverage-japan':   { title: 'LEVERAGE — JAPAN MARGIN TRADING' },
  'leverage-us':      { title: 'LEVERAGE — US MARGIN, FUTURES & OPTIONS' },
  'liquidity-china-flow': { title: 'LIQUIDITY — CHINA · FLOW: NATIONAL TEAM' },
  transcripts:        { title: 'EARNINGS TRANSCRIPT AGENT' },
  sources:            { title: 'DATA VALIDITY TERMINAL' },
};

/** Map sector overview view id → sectorId */
export const SECTOR_OVERVIEW_IDS = {
  'overview': 'overview',
};
